"""add is_active to orders

Revision ID: 351c6f088270
Revises: 9a9f8785b247
Create Date: 2023-01-21 21:08:38.852495

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "351c6f088270"
down_revision = "9a9f8785b247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "is_active")
    # ### end Alembic commands ###
